"""temp table

Revision ID: d3cd31925a6a
Revises: a9783f94aa02
Create Date: 2023-08-24 10:25:52.837563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3cd31925a6a'
down_revision: Union[str, None] = 'a9783f94aa02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('exp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('username')
    )
    op.create_unique_constraint("unique_email", 'users', ['email'])
    op.create_unique_constraint("unique_username", 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_email", 'users', type_='unique')
    op.drop_constraint("unique_username", 'users', type_='unique')
    op.drop_table('temp_users')
    # ### end Alembic commands ###
